"""add purpose to document_requests

Revision ID: 4f63b6d2fdcb
Revises: 0003_fix_refresh_tokens
Create Date: 2026-04-28 09:26:34.368830
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4f63b6d2fdcb"
down_revision = "0003_fix_refresh_tokens"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_requests", sa.Column("purpose", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_requests", "purpose")
    # ### end Alembic commands ###
